name: Magazine Article Collector

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build: # 我们把任务名从 collect 改为 build，更符合语义
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone source repository
        run: git clone --depth 1 https://github.com/hehonghui/awesome-english-ebooks.git source_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 ebooklib pdfplumber nltk markdown2 jinja2

      - name: Run magazine collector script
        run: python ./.github/scripts/collector.py

      - name: DEBUG - List all generated files
        if: always()
        run: ls -R

      # 官方部署步骤 1: 将生成的 docs 文件夹打包成一个 "artifact"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy: # 新增一个专门用于部署的 job
    needs: build # 确保 build 任务成功后才运行
    permissions:
      pages: write      # 允许向 GitHub Pages 写入
      id-token: write   # 允许 OIDC 认证
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 设置部署环境的URL
    runs-on: ubuntu-latest
    steps:
      # 官方部署步骤 2: 从 "artifact" 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
