name: Magazine Article Collector

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 检出你自己的仓库代码到 'local_repo' 文件夹
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          path: local_repo

      # 步骤2: 检出源仓库到 'source_repo_1' 文件夹
      - name: Checkout source repository with LFS
        uses: actions/checkout@v4
        with:
          repository: hehonghui/awesome-english-ebooks
          path: source_repo_1
          lfs: true
          fetch-depth: 1 # 拉取最新即可，LFS文件会完整下载

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ebooklib beautifulsoup4 markdown2 jinja2 lxml

      # 步骤3: 从工作区根目录运行脚本，使用明确的相对路径
      - name: Run collector script
        env:
          # 将工作区根目录的绝对路径注入到环境变量中
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: python local_repo/.github/scripts/collector.py

      # 步骤4: 上传产物，使用明确的相对路径
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: local_repo/docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
