name: Magazine Article Collector

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 【修复】检出你自己的仓库代码，并放到一个叫 'local_repo' 的独立文件夹里
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          path: local_repo

      # 步骤2: 【修复】检出源仓库，并放到一个叫 'source_repo_1' 的独立文件夹里
      - name: Checkout source repository with LFS
        uses: actions/checkout@v4
        with:
          repository: hehonghui/awesome-english-ebooks
          path: source_repo_1
          lfs: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ebooklib beautifulsoup4 markdown2 jinja2

      # 步骤3: 【修复】进入你自己的代码文件夹，然后再运行脚本
      - name: Run collector MVP script
        working-directory: ./local_repo # 关键：切换工作目录到你的代码所在地
        run: python .github/scripts/collector_mvp.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传产物的路径也需要相应更新
          path: ./local_repo/docs 

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
